In [ ]:
import tensorflow as tf

from tensorflow.keras import layers , models # For building neural network models 
import matplotlib.pyplot as plt # For plotting graphs and visualizations

In [4]:
print(tf.__version__)

2.20.0


In [6]:
# load dataset (MNIST dataset of handwritten digits)

(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


X_train: images in the training set (usually 60,000 images), each is a 28x28 grayscale image.

y_train: labels (correct digit 0-9) for each training image.

X_test: images in the test set (usually 10,000 images) used to evaluate the model.

y_test: labels for the test images.

In [9]:
#normalize the data
X_train = X_train.astype("float32") / 255.0   #astype("float32") converts the image pixel values from integers to floating-point numbers.                                            
X_test = X_test.astype("float32") / 255.0     #Pixel values in MNIST images range from 0 to 255 (since each pixel is 8-bit grayscale).
                                              #Dividing by 255.0 scales the values to the range 0.0 to 1.0.

The numbers like 0.0 are pixel brightness values scaled between 0 and 1.

0.0 means the pixel is black (no brightness).

Numbers closer to 1.0 mean brighter pixels (whiter).

In [10]:
print(X_train)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
