In [17]:
import numpy as np
a = np.array([0,1,2,3,4,5])
print(a)

[0 1 2 3 4 5]


In [19]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
a = np.arange(0, 10, 2)   #Arrange from 0 to 10 with step 2
print(a)

[0 2 4 6 8]


In [27]:
a = np.array([0,1,2,3,4,5])

print("Original Array ",a)

b = a.reshape(2,3)
print("Reshaped Array" ,b)

Original Array  [0 1 2 3 4 5]
Reshaped Array [[0 1 2]
 [3 4 5]]


In [31]:
arr = np.array([1,2,3,4])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

2.5
2.5
1.118033988749895


In [159]:

a = np.random.rand()
print(a)

b= np.random.rand(5)
print(b)

c = np.random.rand(2,3)
print(c)

x = np.random.randint(1, 10)
print(x)

y = np.random.randint(0, 100, size= 5)
print(y)

z = np.random.randint(0, 50, size= (3,4))
print(z)
otp  = np.random.randint(100000, 999999)
print(otp)

0.7886366541341739
[0.38312676 0.69404701 0.76023614 0.97032037 0.17114945]
[[0.09743115 0.76144808 0.8103726 ]
 [0.89175122 0.91372845 0.32462619]]
1
[ 2  7 81 92 29]
[[33 15 15 40]
 [ 8 36 39 22]
 [21 13 14 16]]
972992
